CidProject/urls.py
from django.urls import path, re_path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
from django.views.static import serve
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.models import User
# from django_otp.admin import OTPAdminSite
# from django_otp.plugins.otp_totp.models import TOTPDevice
# from django_otp.plugins.otp_totp.admin import TOTPDeviceAdmin

# class OTPAdmin(OTPAdminSite):
#     pass

# admin_site = OTPAdmin(name='OTPAdmin')
# admin_site.register(User)
# admin_site.register(TOTPDevice, TOTPDeviceAdmin)
#from two_factor.urls import urlpatterns as tf_urls
urlpatterns = i18n_patterns(
     path('admin/', admin.site.urls),
    #path('two_factor/', include(('admin_two_factor.urls', 'admin_two_factor'), namespace='two_factor-one')),
    path('', include('cidApp.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),
    prefix_default_language=True,
    #path('mfa/', include(tf_urls)),
)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
   

cidApp/urls.py
from django.urls import path
from django.conf.urls.i18n import set_language

#Built in library for auth views
from django.contrib.auth import views as auth_views
from .crud import(
    AgencyListView,
    agency_create,
    agency_update,
    agency_delete,
)
from .user_management import(
    Login_View,
    Logout_View,
    RegisterUsers,
    UserListsView,
    EditUserView,
    DeleteUserView,
)

from .views import(
    HotLineAndWebView,
    DetailSubject,
      CreateReportWebView,
      ViewAllReport,
      CreateReportWebCallView,
      ReportDetail,
      EditReport,
      EditReportComment,
      EditReportReview,
      SyncSubjectsView,
      DetailCall,
      EnableMFAView,
      DisableMFAView,
      MFAVerificationView,
    )

urlpatterns = [
        #Call API from Web form to insert local database
    path('call-api/', SyncSubjectsView.as_view(), name= 'call-api'),
    path('<int:user_id>/enable-mfa/', EnableMFAView.as_view(), name='enable-mfa'),
    path('<int:user_id>/disable-mfa/', DisableMFAView.as_view(), name='disable-mfa'),
    path('mfa-verify/', MFAVerificationView.as_view(), name='verify-mfa'),
    
        #Hotline and Subjectdetail webview
    path('', HotLineAndWebView.as_view(), name='records'),
    
    path('call-details/<int:pk>/', DetailCall.as_view(), name='detail_call'),
    path('subject_details/<int:pk>/', DetailSubject.as_view(), name='detail_subject'),
    
        #User Managament

    path('login/', Login_View.as_view(), name='login'),
    path('logout/', Logout_View.as_view(), name='logout'),
    path('<int:pk>/edit-user/', EditUserView.as_view(), name='change'),
    path('users/user-list/', UserListsView.as_view(), name='user-list'),
    path('new/add-account/', RegisterUsers.as_view(), name='user-register'),
    path('<int:pk>/delete-user/',DeleteUserView.as_view(), name='delete-user' ),
    
    
        #CRUD URL Agency
    path('agency-create/',agency_create, name= 'create-agency' ),
    path('agency-list/',AgencyListView.as_view(), name ='agency-list'),
    path('<int:pk>/agency-update/', agency_update, name ='agency-update'),
    path('<int:pk>/agency-delete/', agency_delete, name ='agency-delete'),
    
    
    #CRUD URL REPORT
    path('report-list/', ViewAllReport.as_view(), name='report-list'),
    path('add/new-report/',CreateReportWebView.as_view(), name='new-report'),
    path('add/new-report/<int:web_id>/',CreateReportWebCallView.as_view(), name ='report-web'),
     
    #CRUD for Report 
    
    path('<pk>/report-details', ReportDetail.as_view(), name='report-detail'),
    path('report/<int:report_id>/', EditReport.as_view(), name='edit_report'),
    path('report-comment/<int:report_id>/', EditReportComment.as_view(), name='comment_report'),
    
    path('report-review/<int:report_id>/',EditReportReview.as_view(), name='review_report'),
    
    
    
    # Reset password in case users forgot the password
    
    path("password_reset/",auth_views.PasswordResetView.as_view(
        template_name ='users/reset_email_password.html',
        email_template_name ='users/password_reset_email.html',
        ), name='reset_password'),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name = 'users/password_reset_done.html'
            ), name='password_reset_done'
    ),
    path(
        "reset/<uidb64>/<token>/",
         auth_views.PasswordResetConfirmView.as_view(
             template_name ='users/password_reset_confirm.html'
             ), name='password_reset_confirm'
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name ='users/password_reset_complete.html'
            ), name='password_reset_complete'
    ),
    
]

cidApp/forms.py
 
#from msilib.schema import File
from django import forms
# from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth.models import User,Group
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

from .models import Agency, Comments, FileAttch, Intial, Report, Staff, Subject, TextAttach, ReportReviewed
User = get_user_model()
# from django.contrib.auth.models import User
# from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
# from admin_two_factor.models import TwoFactorVerification
# from django.contrib.auth.forms import PasswordResetForm,SetPasswordForm
# """User Registration form"""


# # class CreateTwoFactorForms(forms.ModelForm):
# #     class Meta:
# #         model = TwoFactorVerification
# #         fields =['user']

# class ResetPasswordForm(SetPasswordForm):
#     new_password1 = forms.CharField(
#         required=False,
#         widget=forms.PasswordInput,
#         label="New Password One"
#     )
#     new_password2 = forms.CharField(
#         required=False,
#         widget=forms.PasswordInput,
#         label="New Password Confirm One"
#     )
   
#     def clean(self):
#         cleaned_data = super().clean()
#         new_password1 = cleaned_data.get("new_password1")
#         new_password2 = cleaned_data.get("new_password2")

#         if new_password1 and new_password2:
#             if new_password1 != new_password2:
#                 raise forms.ValidationError("The two password fields didn’t match.")
#         return cleaned_data


class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=100,
                                 required=True,
                                 widget=forms.TextInput(attrs={'placeholder': _('First Name'),
                                                               'class': 'form-control',
                                                               }))
    last_name = forms.CharField(max_length=100,
                                required=True,
                                widget=forms.TextInput(attrs={'placeholder': _('Last Name'),
                                                              'class': 'form-control',
                                                              }))
    # username = forms.CharField(max_length=100,
    #                            required=True,
    #                            widget=forms.TextInput(attrs={'placeholder': 'Username',
    #                                                          'class': 'form-control',
    #                                                          }))
    email = forms.EmailField(required=True,
                             widget=forms.TextInput(attrs={'placeholder': 'Email',
                                                           'class': 'form-control',
                                                           }))
    #permision = forms.ModelChoiceField(queryset=Group.objects.all(), required=True, widget=forms.Select(attrs={'class': 'form-control'}))
    #agency = forms.ModelChoiceField(queryset=Agency.objects.all(), required=True, widget=forms.Select(attrs={'class': 'form-control'}))
    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput(attrs={'placeholder': 'Password',
                                                                  'class': 'form-control',
                                                                  'data-toggle': 'password',
                                                                  'id': 'password',
                                                                  }))
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password',
                                                                  'class': 'form-control',
                                                                  'data-toggle': 'password',
                                                                  'id': 'password',
                                                                  }))
    

    class Meta:
        model =User
        fields = ['first_name', 'last_name', 'email','password1', 'password2']
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError(_("This email is already taken. Please add another valid Email"))
        return email
    def save(self, commit=True):
        user = super().save(commit=False)
        user.username = user.email
        if commit:
            user.save()
        return user

class LoginForm(AuthenticationForm):
    username = forms.EmailField(
        widget=forms.EmailInput(attrs={
            'autofocus': True,
            'placeholder': 'Email',
            'class': 'form-control'
        })
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'placeholder': '******',
            'class': 'form-control',
            'data-toggle': 'password',
            'id': 'password',
        })
    )

    def clean(self):
        email = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if email and password:
            try:
                user = User.objects.get(email=email)
                if not user.check_password(password):
                    raise forms.ValidationError(_('Invalid email or password'))
            except User.DoesNotExist:
                raise forms.ValidationError(_('Invalid email or password'))

        return super().clean()
    
# class CreateRecordsForm(forms.ModelForm):
#     class Meta:
#         model = Subjects
#         exclude = ['created_at', 'updated_at']

#     def __init__(self, *args, **kwargs):
#         super(CreateRecordsForm, self).__init__(*args, **kwargs)
#         for field_name, field in self.fields.items():
#             field.widget.attrs.update({'class': 'form-control'})
        
# class RecordsForm(forms.ModelForm):
#     class Meta:
#         model = Records
#         fields = '__all__'

# class ReferencesForm(forms.ModelForm):
#     class Meta:
#         model = References
#         fields = '__all__'

# class UserEditForm(forms.ModelForm):
#     class Meta:
#         model =Staff
#         fields = [ 'agency']
#     def __init__(self, *args, **kwargs):
#         super(UserEditForm, self).__init__(*args, **kwargs)
#         for field_name, field in self.fields.items():
#             field.widget.attrs.update({'class': 'form-control'})
    
class UserEditForm(forms.ModelForm):
   
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

    def __init__(self, *args, **kwargs):
        super(UserEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})
            
class AgencyForm(forms.Form):
   agency = forms.ModelChoiceField(
        queryset=Agency.objects.all(),
         empty_label=_("Select Agency"),
        required=True,
        widget=forms.Select(attrs={'class': 'form-control'}, )
    )
   empty_field ='Select Agency'
   def __init__(self, *args, **kwargs):
        super(AgencyForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})
            
class GroupForm(forms.Form):
    groups = forms.ModelChoiceField(
        queryset=Group.objects.all(),
        empty_label=_("Select Permision"),
        required=True,
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    
    def __init__(self, *args, **kwargs):
        super(GroupForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})
  
             
class StaffEditForm(forms.ModelForm):
    class Meta:
        model = Staff
        fields = ['agency']  # Add any other fields you want to edit
       
           
    def __init__(self, *args, **kwargs):
        super(StaffEditForm, self).__init__(*args, **kwargs)
        #self.fields['agency'].empty_label = "Select Agency"  # Set the initial option text
        for field_name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'}) 
                  
class GroupEditForm(forms.Form):
    groups = forms.ModelChoiceField(
        queryset=Group.objects.all(),
        required=True,
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    def __init__(self, *args, **kwargs):
        super(GroupEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})

            
class InitialForm(forms.ModelForm):
    class Meta:
        model = Intial 
        fields = ['source', 'information_source',]
        
    def __init__(self, *args, **kwargs):
        super(InitialForm, self).__init__(*args, **kwargs)
        
        for field_name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})
        self.fields['information_source'].required = False

class SubjectForm(forms.ModelForm):
    class Meta:
        model = Subject 
        fields = ('__all__')
        widgets = {
            'dob': forms.DateInput(attrs={'type': 'date'}),

templates/dashproject/pages/comments.html
{% load static i18n %} 
<div class="container">
  <div class="row">
    <div class="col">
      <form action="POST" method="post">
        {% csrf_token %}
        <div class="form-group">
          <label for="">{% trans 'Comment' %}</label>
          {{comments_form.comment}}
        </div>

        <button class="btn btn-primary mb-1 mt-1 toastrDefaultSuccess" type="submit" name="comments_form">
          <i class="fa fa-plus"> </i><span class="text-uppercase">{% trans 'Add New Comment'%}</span>
        </button>
      </form>
    </div>
  </div>
  <div class="row">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">{% trans 'Analyst Comments(s)'%}</th>
          <th scope="col">{% trans 'User'%}</th>
          <th scope="col">{% trans 'Update at'%}</th>
        </tr>
      </thead>
      <tbody>
        {%for comments in comments %}
        <tr>
          <td scope="row">{{comments.comment}}</td>
          <td>{{comments.user.first_name}}</td>
          <td>{{comments.updated_at}}</td>
        </tr>
        {%endfor%}
      </tbody>
    </table>
  </div>
</div>

templates/dashproject/pages/create_records_forms.html
{%extends 'dashproject/AdminLTE/layout.html'%} {% load static %}
 {% block content %}
 <div class="container">
  <div class="row">
    <h2>Create a new Record</h2>
    <form method="post">
      {% csrf_token %} {{ form.as_p }}
      <button type="submit" class="btn btn-success">Save</button>
    </form>
  </div>
 </div>
{% endblock content %}

templates/dashproject/pages/detail_call.html
<h2>Hotline Details</h2>

<table>
    <tr>
        <th>ID</th>
        <td>{{ object.id }}</td>
    </tr>
    <tr>
        <th>Name</th>
        <td>{{ object.file_path}}</td>
    </tr>
    <tr>
        <th>Create</th>
        <td>{{ object.created_at }}</td>
    </tr>
    <!-- Add other fields as needed -->
</table>

templates/dashproject/pages/detail_subject.html
{% load static i18n %}
{% block content %}
<div class="card">
  <div class="card-body">
    <div class="card-header">
      <h4>{% trans "Subject you are giving information about" %}</h4>
    </div>
    <p class="text-mute">{% trans "First Name" %}</p>
    <p><strong><span id="name-data"></span></strong></p>

    <p class="text-mute">{% trans "Last Name" %}</p>
    <p><strong><span id="last-data"></span></strong></p>

    <p class="text-mute">{% trans "Middle Name" %}</p>
    <p><strong><span id="middle-name-data"></span></strong></p>

    <p class="text-mute">{% trans "Nick Name" %}</p>
    <p><strong><span id="nick-name-data"></span></strong></p>

    <p class="text-mute">{% trans "Description of Subject" %}</p>
    <p><strong><span id="description-data"></span></strong></p>

    <p class="text-mute">{% trans "Business Name" %}</p>
    <p><strong><span id="business-name-data"></span></strong></p>

    <h4>{% trans "The address of the person or business" %}</h4>
    <hr>
    <p class="text-mute">{% trans "Address" %}</p>
    <p><strong><span id="address-data"></span></strong></p>

    <p class="text-mute">{% trans "Post Code" %}</p>
    <p><strong><span id="post-code-data"></span></strong></p>

    <p class="text-mute">{% trans "Country" %}</p>
    <p><strong><span id="country-data"></span></strong></p>

    <p class="text-mute">{% trans "Phone Number" %}</p>
    <p><strong><span id="phone-data"></span></strong></p>

    <h4>{% trans "Transportation information" %}</h4>
    <hr>
    <p class="text-mute">{% trans "Vehicles" %}</p>
    <p><strong><span id="vehicle-data"></span></strong></p>

    <p class="text-mute">{% trans "Flight and Routing" %}</p>
    <p><strong><span id="routing-data"></span></strong></p>

    <p class="text-mute">{% trans "Ferry crossings" %}</p>
    <p><strong><span id="ferry-data"></span></strong></p>

    <p class="text-mute">{% trans "Vessel and Yachts" %}</p>
    <p><strong><span id="vessel-data"></span></strong></p>

    <p class="text-mute">{% trans "Cargo and Fast parcel" %}</p>
    <p><strong><span id="cargo-data"></span></strong></p>

    <p class="text-mute">{% trans "Other Transport and travels" %}</p>
    <p><strong><span id="other-trans-data"></span></strong></p>

    <h4>{% trans "The approximate age or date of birth and nationality of the person" %}</h4>
    <hr>
    <p class="text-mute">{% trans "Approximate Age" %}</p>
    <p><strong><span id="approx-age-data"></span></strong></p>

    <p class="text-mute">{% trans "Date of Birth" %}</p>
    <p><strong><span id="dob-data"></span></strong></p>

    <p class="text-mute">{% trans "Nationality" %}</p>
    <p><strong><span id="nat-data"></span></strong></p>

    <h4>{% trans "Names of others involved" %}</h4>
    <hr>
    <p class="text-mute">{% trans "Name of any other involved" %}</p>
    <p><strong><span id="any-other-data"></span></strong></p>

    <h4>{% trans "Event details" %}</h4>
    <hr>
    <p class="text-mute">{% trans "What is taking place?" %}</p>
    <p><strong><span id="what-data"></span></strong></p>

    <p class="text-mute">{% trans "Where is happening?" %}</p>
    <p><strong><span id="location-data"></span></strong></p>

    <p class="text-mute">{% trans "How often does this happen?" %}</p>
    <p><strong><span id="quando-data"></span></strong></p>

    <p class="text-mute">{% trans "How long has it been going on?" %}</p>
    <p><strong><span id="how-long-data"></span></strong></p>

    <h4>{% trans "Additional information" %}</h4>
    <hr>
    <p class="text-mute">{% trans "Other information that would be relevant" %}</p>
    <p><strong><span id="other-infor-data"></span></strong></p>

    <p class="text-mute">{% trans "Your connection with the person or business" %}</p>
    <p><strong><span id="your-connection-data"></span></strong></p>

    <p class="text-mute">{% trans "Are you still connected to the person or business?" %}</p>
    <p><strong><span id="still-connect-data"></span></strong></p>

    <h4>{% trans "Involvement details" %}</h4>
    <hr>
    <p class="text-mute">{% trans "How did you obtain this information?" %}</p>
    <p><strong><span id="how-did-data"></span></strong></p>

    <p class="text-mute">{% trans "Does anyone else know this information? If so, how many?" %}</p>
    <p><strong><span id="others-know-information-data"></span></strong></p>

    <p class="text-mute">{% trans "How many?" %}</p>
    <p><strong><span id="how-many-data"></span></strong></p>

    <p class="text-mute">{% trans "Will it affect you if we use the information?" %}</p>
    <p><strong><span id="affect-information-data"></span></strong></p>

    <h4>{% trans "Reporter details" %}</h4>
    <hr>
    <p class="text-mute">{% trans "First Name" %}</p>
    <p><strong><span id="an-first-name-data"></span></strong></p>

    <p class="text-mute">{% trans "Last Name" %}</p>
    <p><strong><span id="an-last-name-data"></span></strong></p>

    <p class="text-mute">{% trans "Middle Name" %}</p>
    <p><strong><span id="an-middle-name-data"></span></strong></p>

    <p class="text-mute">{% trans "Telephone number(s) including STD" %}</p>
    <p><strong><span id="an-phone-number-data"></span></strong></p>

    <p class="text-mute">{% trans "Email" %}</p>
    <p><strong><span id="an-email-data"></span></strong></p>

    <p class="text-mute">{% trans "Would you like someone to call you back?" %}</p>
    <p><strong><span id="ligar-data"></span></strong></p>
  </div>
</div>
{% endblock %}

templates/dashproject/pages/file_form.html
 <form method="POST" action="" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                  {{ file_form.path }}
                </div>
                <button type="submit" class="btn btn-primary mt-1" name="file_form">
                  Submit
                </button>
</form>

templates/dashproject/pages/initial.html
    {% load i18n %}
    <form method="POST" action="">
                  {% csrf_token %}
                  <div class="card">
                    <div class="card-header">{% trans 'Form for Initialization' %}</div>
                    <div class="card-body">
                      <div class="form-group">
                        <label for="id_source">{% trans 'Source' %}</label>
                        {{ initial_form.source }}
                      </div>

                      <div class="form-group">
                        <label for="id_information_source">{% trans 'Information Source' %}</label>
                        {{ initial_form.information_source }}
                      </div>
                    </div>
                  </div>
                  <button type="submit" class="btn btn-primary mt-1" name="initial_form">
                    {% trans 'Submit to next proccess' %}
                  </button>
    </form>

templates/dashproject/pages/initial_page.html
{% extends 'dashproject/base/layout.html' %}
{% load i18n %}
<div class="container-fluid">

    {% block content %}
<p>Step {{ wizard.steps.step1 }} of {{ wizard.steps.count }}</p>
<form action="" method="post">{% csrf_token %}
<table>
{{ wizard.management_form }}
{% if wizard.form.forms %}
    {{ wizard.form.management_form }}
    {% for form in wizard.form.forms %}
        {{ form.as_table }}
    {% endfor %}
{% else %}
    {{ wizard.form }}
{% endif %}
</table>
{% if wizard.steps.prev %}
<button name="wizard_goto_step" type="submit" value="{{ wizard.steps.first }}">{% translate "first step" %}</button>
<button name="wizard_goto_step" type="submit" value="{{ wizard.steps.prev }}">{% translate "prev step" %}</button>
{% endif %}
<input type="submit" value="{% translate "submit" %}"/>
</form>
{% endblock %}
</div>
</div>

templates/dashproject/pages/review.html
<div class="container">
  <div class="row">
    <div class="bg bg-primary"> 
      <div class="row">
        <div class="col-md-9">
          <p>
            Carefully review each section of the record below and confirm the details.
            You must to confirm all the sections in order to complete the record.
          </p>
        </div>
        <div class="col-md-3">
          <button class="bg bg-dark">Analyst Comment(s)</button>
        </div>
      </div>  
    </div>
   </div>
   <div class="row">
    <p>Initial</p>
  
   </div>
</div>

templates/dashproject/pages/subject.html
{% load i18n %}
<form method="POST" action="">
    {% csrf_token %}
    <div class="card"></div>
    <div class="card-header">{% trans "Subject Form" %}</div>
    <div class="card-body">
        <div class="form-group">
            <label for="id_first_name">{% trans "First Name" %}</label>
            {{ subject_form.first_name }}
        </div>

        <div class="form-group">
            <label for="id_last_name">{% trans "Last Name" %}</label>
            {{ subject_form.last_name }}
        </div>

        <div class="form-group">
            <label for="id_gender">{% trans "Gender" %}</label>
            {{ subject_form.gender }}
        </div>

        <div class="form-group">
            <label for="id_pob">{% trans "Place of Birth" %}</label>
            {{ subject_form.pob }}
        </div>

        {% comment %} <div class="form-group">
            <label for="id_nick_name">{% trans "Nick Name" %}</label>
            {{ subject_form.nick_name }}
        </div> {% endcomment %}

        <div class="form-group">
            <label for="id_dob">{% trans "Date of Birth" %}</label>
            {{ subject_form.dob }}
        </div>

        <div class="form-group">
            <label for="id_nationality">{% trans "Nationality" %}</label>
            {{ subject_form.nationality }}
        </div>

        <div class="form-group">
            <label for="id_identification">{% trans "Identification" %}</label>
            {{ subject_form.identification }}
        </div>

        <div class="form-group">
            <label for="id_idNumber">{% trans "ID Number" %}</label>
            {{ subject_form.idNumber }}
        </div>

        <div class="form-group">
            <label for="id_address">{% trans "Home Address" %}</label>
            {{ subject_form.address }}
        </div>

        <div class="form-group">
            <label for="id_business_name">{% trans "Business Name" %}</label>
            {{ subject_form.business_name }}
        </div>

        <div class="form-group">
            <label for="id_busaddress">{% trans "Business Address" %}</label>
            {{ subject_form.busaddress }}
        </div>

        <div class="form-group">
            <label for="id_bin_tin">{% trans "BIN or TIN" %}</label>
            {{ subject_form.bin_tin }}
        </div>

        <div class="form-group">
            <label for="id_phone_num">{% trans "Telephone" %}</label>
            {{ subject_form.phone_num }}
        </div>

        <div class="form-group">
            <label for="id_description_subject">{% trans "Description" %}</label>
            {{ subject_form.description_subject }}
        </div>

        <div class="form-group">
            <label for="id_coveyance">{% trans "Conveyance" %}</label>
            {{ subject_form.coveyance }}
        </div>

        <div class="form-group">
            <label for="id_cov_description">{% trans "Conveyance Description" %}</label>
            {{ subject_form.cov_description }}
        </div>
    </div>

    <div class="card-footer">
        <button type="submit" class="btn btn-primary mt-1" name="subject_form">
            {% trans "Submit Subject" %}
        </button>
        <a href="{% url 'report-list' %}" class="btn btn-warning mt-1">{% trans "Save" %}</a>
    </div>
</form>