CidProject/urls.py
from django.urls import path, re_path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
from django.views.static import serve
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.models import User
# from django_otp.admin import OTPAdminSite
# from django_otp.plugins.otp_totp.models import TOTPDevice
# from django_otp.plugins.otp_totp.admin import TOTPDeviceAdmin

# class OTPAdmin(OTPAdminSite):
#     pass

# admin_site = OTPAdmin(name='OTPAdmin')
# admin_site.register(User)
# admin_site.register(TOTPDevice, TOTPDeviceAdmin)
#from two_factor.urls import urlpatterns as tf_urls
urlpatterns = i18n_patterns(
     path('admin/', admin.site.urls),
    #path('two_factor/', include(('admin_two_factor.urls', 'admin_two_factor'), namespace='two_factor-one')),
    path('', include('cidApp.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),
    prefix_default_language=True,
    #path('mfa/', include(tf_urls)),
)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
   

cidApp/urls.py
from django.urls import path
from django.conf.urls.i18n import set_language

#Built in library for auth views
from django.contrib.auth import views as auth_views
from .crud import(
    AgencyListView,
    agency_create,
    agency_update,
    agency_delete,
)
from .user_management import(
    Login_View,
    Logout_View,
    RegisterUsers,
    UserListsView,
    EditUserView,
    DeleteUserView,
)

from .views import(
    HotLineAndWebView,
    DetailSubject,
      CreateReportWebView,
      ViewAllReport,
      CreateReportWebCallView,
      ReportDetail,
      EditReport,
      EditReportComment,
      EditReportReview,
      SyncSubjectsView,
      DetailCall,
      EnableMFAView,
      DisableMFAView,
      MFAVerificationView,
    )

urlpatterns = [
        #Call API from Web form to insert local database
    path('call-api/', SyncSubjectsView.as_view(), name= 'call-api'),
    path('<int:user_id>/enable-mfa/', EnableMFAView.as_view(), name='enable-mfa'),
    path('<int:user_id>/disable-mfa/', DisableMFAView.as_view(), name='disable-mfa'),
    path('mfa-verify/', MFAVerificationView.as_view(), name='verify-mfa'),
    
        #Hotline and Subjectdetail webview
    path('', HotLineAndWebView.as_view(), name='records'),
    
    path('call-details/<int:pk>/', DetailCall.as_view(), name='detail_call'),
    path('subject_details/<int:pk>/', DetailSubject.as_view(), name='detail_subject'),
    
        #User Managament

    path('login/', Login_View.as_view(), name='login'),
    path('logout/', Logout_View.as_view(), name='logout'),
    path('<int:pk>/edit-user/', EditUserView.as_view(), name='change'),
    path('users/user-list/', UserListsView.as_view(), name='user-list'),
    path('new/add-account/', RegisterUsers.as_view(), name='user-register'),
    path('<int:pk>/delete-user/',DeleteUserView.as_view(), name='delete-user' ),
    
    
        #CRUD URL Agency
    path('agency-create/',agency_create, name= 'create-agency' ),
    path('agency-list/',AgencyListView.as_view(), name ='agency-list'),
    path('<int:pk>/agency-update/', agency_update, name ='agency-update'),
    path('<int:pk>/agency-delete/', agency_delete, name ='agency-delete'),
    
    
    #CRUD URL REPORT
    path('report-list/', ViewAllReport.as_view(), name='report-list'),
    path('add/new-report/',CreateReportWebView.as_view(), name='new-report'),
    path('add/new-report/<int:web_id>/',CreateReportWebCallView.as_view(), name ='report-web'),
     
    #CRUD for Report 
    
    path('<pk>/report-details', ReportDetail.as_view(), name='report-detail'),
    path('report/<int:report_id>/', EditReport.as_view(), name='edit_report'),
    path('report-comment/<int:report_id>/', EditReportComment.as_view(), name='comment_report'),
    
    path('report-review/<int:report_id>/',EditReportReview.as_view(), name='review_report'),
    
    
    
    # Reset password in case users forgot the password
    
    path("password_reset/",auth_views.PasswordResetView.as_view(
        template_name ='users/reset_email_password.html',
        email_template_name ='users/password_reset_email.html',
        ), name='reset_password'),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name = 'users/password_reset_done.html'
            ), name='password_reset_done'
    ),
    path(
        "reset/<uidb64>/<token>/",
         auth_views.PasswordResetConfirmView.as_view(
             template_name ='users/password_reset_confirm.html'
             ), name='password_reset_confirm'
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name ='users/password_reset_complete.html'
            ), name='password_reset_complete'
    ),
    
]

cidApp/forms.py
 
#from msilib.schema import File
from django import forms
# from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth.models import User,Group
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

from .models import Agency, Comments, FileAttch, Intial, Report, Staff, Subject, TextAttach, ReportReviewed
User = get_user_model()
# from django.contrib.auth.models import User
# from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
# from admin_two_factor.models import TwoFactorVerification
# from django.contrib.auth.forms import PasswordResetForm,SetPasswordForm
# """User Registration form"""


# # class CreateTwoFactorForms(forms.ModelForm):
# #     class Meta:
# #         model = TwoFactorVerification
# #         fields =['user']

# class ResetPasswordForm(SetPasswordForm):
#     new_password1 = forms.CharField(
#         required=False,
#         widget=forms.PasswordInput,
#         label="New Password One"
#     )
#     new_password2 = forms.CharField(
#         required=False,
#         widget=forms.PasswordInput,
#         label="New Password Confirm One"
#     )
   
#     def clean(self):
#         cleaned_data = super().clean()
#         new_password1 = cleaned_data.get("new_password1")
#         new_password2 = cleaned_data.get("new_password2")

#         if new_password1 and new_password2:
#             if new_password1 != new_password2:
#                 raise forms.ValidationError("The two password fields didn’t match.")
#         return cleaned_data


class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=100,
                                 required=True,
                                 widget=forms.TextInput(attrs={'placeholder': _('First Name'),
                                                               'class': 'form-control',
                                                               }))
    last_name = forms.CharField(max_length=100,
                                required=True,
                                widget=forms.TextInput(attrs={'placeholder': _('Last Name'),
                                                              'class': 'form-control',
                                                              }))
    # username = forms.CharField(max_length=100,
    #                            required=True,
    #                            widget=forms.TextInput(attrs={'placeholder': 'Username',
    #                                                          'class': 'form-control',
    #                                                          }))
    email = forms.EmailField(required=True,
                             widget=forms.TextInput(attrs={'placeholder': 'Email',
                                                           'class': 'form-control',
                                                           }))
    #permision = forms.ModelChoiceField(queryset=Group.objects.all(), required=True, widget=forms.Select(attrs={'class': 'form-control'}))
    #agency = forms.ModelChoiceField(queryset=Agency.objects.all(), required=True, widget=forms.Select(attrs={'class': 'form-control'}))
    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput(attrs={'placeholder': 'Password',
                                                                  'class': 'form-control',
                                                                  'data-toggle': 'password',
                                                                  'id': 'password',
                                                                  }))
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password',
                                                                  'class': 'form-control',
                                                                  'data-toggle': 'password',
                                                                  'id': 'password',
                                                                  }))
    

    class Meta:
        model =User
        fields = ['first_name', 'last_name', 'email','password1', 'password2']
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError(_("This email is already taken. Please add another valid Email"))
        return email
    def save(self, commit=True):
        user = super().save(commit=False)
        user.username = user.email
        if commit:
            user.save()
        return user

class LoginForm(AuthenticationForm):
    username = forms.EmailField(
        widget=forms.EmailInput(attrs={
            'autofocus': True,
            'placeholder': 'Email',
            'class': 'form-control'
        })
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'placeholder': '******',
            'class': 'form-control',
            'data-toggle': 'password',
            'id': 'password',
        })
    )

    def clean(self):
        email = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if email and password:
            try:
                user = User.objects.get(email=email)
                if not user.check_password(password):
                    raise forms.ValidationError(_('Invalid email or password'))
            except User.DoesNotExist:
                raise forms.ValidationError(_('Invalid email or password'))

        return super().clean()
    
# class CreateRecordsForm(forms.ModelForm):
#     class Meta:
#         model = Subjects
#         exclude = ['created_at', 'updated_at']

#     def __init__(self, *args, **kwargs):
#         super(CreateRecordsForm, self).__init__(*args, **kwargs)
#         for field_name, field in self.fields.items():
#             field.widget.attrs.update({'class': 'form-control'})
        
# class RecordsForm(forms.ModelForm):
#     class Meta:
#         model = Records
#         fields = '__all__'

# class ReferencesForm(forms.ModelForm):
#     class Meta:
#         model = References
#         fields = '__all__'

# class UserEditForm(forms.ModelForm):
#     class Meta:
#         model =Staff
#         fields = [ 'agency']
#     def __init__(self, *args, **kwargs):
#         super(UserEditForm, self).__init__(*args, **kwargs)
#         for field_name, field in self.fields.items():
#             field.widget.attrs.update({'class': 'form-control'})
    
class UserEditForm(forms.ModelForm):
   
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

    def __init__(self, *args, **kwargs):
        super(UserEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})
            
class AgencyForm(forms.Form):
   agency = forms.ModelChoiceField(
        queryset=Agency.objects.all(),
         empty_label=_("Select Agency"),
        required=True,
        widget=forms.Select(attrs={'class': 'form-control'}, )
    )
   empty_field ='Select Agency'
   def __init__(self, *args, **kwargs):
        super(AgencyForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})
            
class GroupForm(forms.Form):
    groups = forms.ModelChoiceField(
        queryset=Group.objects.all(),
        empty_label=_("Select Permision"),
        required=True,
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    
    def __init__(self, *args, **kwargs):
        super(GroupForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})
  
             
class StaffEditForm(forms.ModelForm):
    class Meta:
        model = Staff
        fields = ['agency']  # Add any other fields you want to edit
       
           
    def __init__(self, *args, **kwargs):
        super(StaffEditForm, self).__init__(*args, **kwargs)
        #self.fields['agency'].empty_label = "Select Agency"  # Set the initial option text
        for field_name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'}) 
                  
class GroupEditForm(forms.Form):
    groups = forms.ModelChoiceField(
        queryset=Group.objects.all(),
        required=True,
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    def __init__(self, *args, **kwargs):
        super(GroupEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})

            
class InitialForm(forms.ModelForm):
    class Meta:
        model = Intial 
        fields = ['source', 'information_source',]
        
    def __init__(self, *args, **kwargs):
        super(InitialForm, self).__init__(*args, **kwargs)
        
        for field_name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})
        self.fields['information_source'].required = False

class SubjectForm(forms.ModelForm):
    class Meta:
        model = Subject 
        fields = ('__all__')
        widgets = {
            'dob': forms.DateInput(attrs={'type': 'date'}),

templates/users/base_css.html
<!-- Font Awesome -->
{%load static%}
<link rel="stylesheet" href="{% static 'dashproject/admin-lte/plugins/fontawesome-free/css/all.min.css'%}" />
<link rel="stylesheet" href="{% static 'dashproject/admin-lte/plugins/flag-icon-css/css/flag-icon.min.css'%}" />

<link href="{% static 'dashproject/admin-lte/dist/img/icon-costume.png'%}" rel="icon" />
<!-- Ionicons -->
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" />
<!-- Tempusdominus Bbootstrap 4 -->
<link rel="stylesheet"
  href="{% static 'dashproject/admin-lte/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css'%}" />
<!-- iCheck -->
<link rel="stylesheet" href="{% static 'dashproject/admin-lte/plugins/icheck-bootstrap/icheck-bootstrap.min.css'%}" />
<!-- JQVMap -->
<link rel="stylesheet" href="{% static 'dashproject/admin-lte/plugins/jqvmap/jqvmap.min.css'%}" />
<!-- Theme style -->
<link rel="stylesheet" href="{% static 'dashproject/admin-lte/dist/css/adminlte.min.css'%}" />
<!-- overlayScrollbars -->
<link rel="stylesheet"
  href="{% static 'dashproject/admin-lte/plugins/overlayScrollbars/css/OverlayScrollbars.min.css'%}" />
<!-- Daterange picker -->
<link rel="stylesheet" href="{% static 'dashproject/admin-lte/plugins/daterangepicker/daterangepicker.css'%}" />
<!-- summernote -->
<link rel="stylesheet" href="{% static 'dashproject/admin-lte/plugins/summernote/summernote-bs4.css'%}" />
<!-- Google Font: Source Sans Pro -->
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet" />
<link rel="stylesheet" href="{% static 'dashproject/admin-lte/dist/css/style.css'%}" />

<!-- DataTables -->
<link rel="stylesheet"
  href="{% static 'dashproject/admin-lte/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css'%}" />
<link rel="stylesheet"
  href="{% static 'dashproject/admin-lte/plugins/datatables-responsive/css/responsive.bootstrap4.min.css'%}" />
<link rel="stylesheet"
  href="{% static 'dashproject/admin-lte/plugins/datatables-buttons/css/buttons.bootstrap4.min.css'%}" />
<title>CID - Costums Intelligence Database</title>

templates/users/base_js.html
{%load static%}
<!-- jQuery -->
<script src="{% static 'dashproject/admin-lte/plugins/jquery/jquery.min.js'%}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'dashproject/admin-lte/plugins/jquery-ui/jquery-ui.min.js'%}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge("uibutton", $.ui.button);
</script>
<!-- Bootstrap 4 -->
<script src="{% static 'dashproject/admin-lte/plugins/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
<!-- ChartJS -->
<script src="{% static 'dashproject/admin-lte/plugins/chart.js/Chart.min.js'%}"></script>
<!-- Sparkline -->
<script src="{% static 'dashproject/admin-lte/plugins/sparklines/sparkline.js'%}"></script>
<!-- JQVMap -->
<script src="{% static 'dashproject/admin-lte/plugins/jqvmap/jquery.vmap.min.js'%}"></script>
<script src="{% static 'dashproject/admin-lte/plugins/jqvmap/maps/jquery.vmap.usa.js'%}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static 'dashproject/admin-lte/plugins/jquery-knob/jquery.knob.min.js'%}"></script>
<!-- daterangepicker -->
<script src="{% static 'dashproject/admin-lte/plugins/moment/moment.min.js'%}"></script>
<script src="{% static 'dashproject/admin-lte/plugins/daterangepicker/daterangepicker.js'%}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static 'dashproject/admin-lte/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js'%}"></script>
<!-- Summernote -->
<script src="{% static 'dashproject/admin-lte/plugins/summernote/summernote-bs4.min.js'%}"></script>
<!-- overlayScrollbars -->
{% comment %}
<script src="{% static 'dashproject/admin-lte/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js'%}"></script>
{% endcomment %}
<!-- AdminLTE App -->
<script src="{% static 'dashproject/admin-lte/dist/js/adminlte.js'%}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static 'dashproject/admin-lte/dist/js/pages/dashboard.js'%}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'dashproject/admin-lte/dist/js/demo.js'%}"></script>

<!-- DataTables  & Plugins -->
<script src="{% static 'dashproject/admin-lte/plugins/datatables/jquery.dataTables.min.js'%}"></script>
<script src="{% static 'dashproject/admin-lte/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js'%}"></script>
<script src="{% static 'dashproject/admin-lte/plugins/datatables-responsive/js/dataTables.responsive.min.js'%}"></script>
<script src="{% static 'dashproject/admin-lte/plugins/datatables-responsive/js/responsive.bootstrap4.min.js'%}"></script>
<script src="{% static 'dashproject/admin-lte/plugins/datatables-buttons/js/dataTables.buttons.min.js'%}"></script>
<script src="{% static 'dashproject/admin-lte/plugins/datatables-buttons/js/buttons.bootstrap4.min.js'%}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.4/jquery-confirm.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>

<script>
  $(document).ready(function () {
    $("#CheckTwoStep").click(function (e) {
      e.preventDefault();
      var btn = $(this);
      var url = btn.data("url");
      var param = {
        url: url,
        form: $("#login-form"),
      };
      AjaxCheckTwoStepVerification(param);
    });
  });

  function AjaxCheckTwoStepVerification(param) {
    $.ajax({
      url: param.url,
      type: "POST",
      async: true,
      data: param.form.serialize(),
      success: function (data) {
        if (data.is_valid) {
          $.confirm({
            title: "Two Step Verification",
            content:
              '<div class="form-group">' +
              "<label>Verification Code: </label>" +
              '<input name="code" type="text" placeholder="Code" class="code form-control" required />' +
              "</div>",
            type: "orange",
            buttons: {
              verify: function () {
                var code = this.$content.find(".code").val();
                if (!code) {
                  $.alert("Provide a valid code");
                  return false;
                }

                $.ajax({
                  url: param.url,
                  type: "PUT",
                  async: true,
                  data: param.form.serialize() + "&code=" + code,
                  beforeSend: function (xhr) {
                    xhr.setRequestHeader("X-CSRFToken", $.cookie("csrftoken"));
                  },
                  success: function (data) {
                    if (data.is_valid) {
                      window.location.href = "{% url 'records' %}"; // Change 'index' to the name of your index URL
                    } else {
                      $.alert(data.message);
                    }
                  },
                  error: function () {
                    $.alert("Error occurred");
                  },
                });
              },
              cancel: function () {},
            },
          });
        } else {
          param.form.submit();
        }
      },
      error: function () {
        showMessage("warning", "Error occurred");
      },
    });
  }
</script>

templates/users/disable_mfa.html
{%include './base_css.html' %}

{% load i18n %}
{% block content %}
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card text-center mt-3">
                <div class="card-header">
                    <h2>{% trans 'Disable Multi-Factor Authentication' %}</h2>
                </div>
                <div class="card-body">
                    {% if is_mfa_enabled %}
                    <p>{% trans 'MFA is currently enabled. Are you sure you want to disable it?' %}</p>
                    <form method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">{% trans 'Disable MFA' %}</button>
                    </form>
                    {% else %}
                    <p>{% trans 'MFA is already disabled for this user.' %}</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/users/enable_mfa.html
{% extends 'dashproject/base/layout.html' %}
{% load static %}
{% load i18n %}
{% block content %}
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card text-center mt-3">
                <div class="card-header">
                    <h2>{% trans 'Multi-Factor Authentication' %}</h2>
                </div>
                <div class="card-body">
                    {% if error %}
                    <p style="color:red;">{{ error }}</p>
                    {% endif %}
                    <p>{% trans 'Scan the QR code below with your Google Authenticator app to enable MFA:' %}</p>
                    <img src="data:image/png;base64,{{ qr_code }}" alt="QR Code" class="mb-3">
                    <form method="post" class="form-group">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="token" class="text-left">
                                {% trans 'Enter the 6-digit code from your app:' %}</label>
                            <div class="input-group">
                                <input type="text" name="token" id="token" class="form-control" required>
                                <div class="input-group-append">
                                    <button type="submit" class="btn btn-info">{% trans 'Enable MFA' %}</button>
                                </div>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/users/password_reset_complete.html
{% load i18n static %}
{% load widget_tweaks %}
{% include 'users/base_css.html' %}

<div class="container mt-5">
    <div class="card">
        <div class="card-header">
            <h4>{% translate "Password Successfully Changed" %}</h4>
        </div>
        <div class="card-body">
            {% block content %}
            <p>{% trans "Your password has been set. You may go ahead and log in now." %}</p>

            <p><a href="{% url 'login' %}" class="btn btn-info">{% trans 'Log in' %}</a></p>
            {% endblock %}
        </div>
    </div>

</div>

templates/users/register.html
{% extends 'dashproject/base/layout.html' %} 
{% load i18n %}
{% load static %} 
{% block content %}
<div class="card">
  <div class="card-body">
    <div class="form-content my-3 p-3">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-7">
            <div class="card shadow-lg border-0 rounded-lg mt-0 mb-5">
              <div class="card-header justify-content-center">
                <h3 class="font-weight-light my-4 text-center">
                  {% trans 'Create New Account'%}
                </h3>
              </div>
              <div class="card-body">
                <form method="POST">
                  {% csrf_token %} {% if form.errors %}
                  <div
                    class="alert alert-danger alert-dismissible"
                    role="alert"
                  >
                    <div id="form_errors">
                      {% for key, value in form.errors.items %}
                      <strong>{{ value }}</strong>
                      {% endfor %}
                    </div>
                    <button
                      type="button"
                      class="close"
                      data-dismiss="alert"
                      aria-label="Close"
                    >
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  {% endif %}
                  <div class="form-row">
                    <div class="col-md-6">
                      <div class="form-group">
                        <label class="small mb-1">{% trans 'First Name'%}</label>
                        {{ form.first_name }}
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group">
                        <label class="small mb-1">{% trans 'Last Name'%}</label>
                        {{ form.last_name }}
                      </div>
                    </div>
                  </div>
                  <div class="form-row">
                    <div class="col-md-6">
                      <div class="form-group">
                        <label class="small mb-1">Email</label>
                        {{ form.email }}
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group">
                        <label class="small mb-1">{% trans 'Permission'%}</label>
                        {{ groups_form.groups }} 
                        {% if groups_form.errors.groups%}
                        <div class="invalid-feedback">
                          {{ groups_form.errors.groups }}
                        </div>
                        {% endif %}
                      </div>
                    </div>
                  </div>
                  <div class="form-group">
                        <label for="id_agency">{% trans 'Agency' %}</label>
                         {{staff_form.agency}}
                  </div>
                 
                  <div class="form-row">
                    <div class="col-md-6">
                      <div class="form-group">
                        <label class="small mb-1">{% trans 'Password'%}</label>
                        {{ form.password1 }} {{ form.errors.password1 }}
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group">
                        <label class="small mb-1">{% trans 'Confirm Password'%}</label>
                        {{ form.password2 }}
                      </div>
                    </div>
                  </div>

                  <div class="form-group mt-4 mb-0">
                    <button type="submit" class="col-md-3 btn btn-dark">
                     {% trans 'Create' %}
                    </button>
                    <br /><br />
                  </div>
                </form>
              </div>
              {% comment %}
              <div class="card-footer text-center">
                <div class="small">
                  <a href="{% url 'login' %}">Have an account? Go to Sign in</a>
                </div>
              </div>
              {% endcomment %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/users/reset_email_password.html
{% load i18n %}
{% load widget_tweaks %}
{% include 'users/base_css.html' %}

<div class="container-fluid d-flex justify-content-center align-items-center  mt-2">
    <div class="card col-12 col-md-8 col-lg-6"> <!-- Adjusted card width for responsiveness -->
        <div class="card-header">{% trans 'Password Recovery' %}</div> <!-- Centered header text -->
        <div class="card-body">
            <form action="" method="post" class="form-group">
                {% csrf_token %}
                <label for="id_email">{% trans 'Email' %}</label>
                <div class="row">
                    <div class="col-md-12"> <!-- Changed column width to full for better alignment -->
                        {{ form.email|add_class:"form-control" }}
                    </div>
                </div>

                <div class="row mt-3"> <!-- Added margin-top for spacing -->
                    <div class="col-md-3"> <!-- Changed column width to full for better alignment -->
                        <button type="submit" class="btn btn-info btn-block">{% trans 'Submit' %}</button>
                        <!-- Added btn-block for full width -->
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>